export interface IUser {
  empCode: string;
  name: string;
  email: string;
  password?: string;
  avatarURL: string;
  admin: boolean;
  phone: string;
  tel: string;
  joinDate: string;
  birthDate: string;
  startWorkTime: string;
  finishWorkTime: string;
  ogarnization: string;
  duty: string;
  level: string;
}

export const tempUser: IUser[] = [
  {
    empCode: "123",
    name: "홍길동",
    email: "123@naver.com",
    password: "qwer1234!",
    avatarURL: "/imgs/202301261737390.jpg",
    admin: false,
    phone: "010-1234-1234",
    tel: "02-123-1234",
    birthDate: "1999.01.01",
    joinDate: "2024.12.01",
    startWorkTime: "09:00:00",
    finishWorkTime: "18:00:00",
    ogarnization: "디자인팀",
    duty: "BX 디자이너",
    level: "팀원",
  },
  {
    empCode: "234",
    name: "관리자",
    email: "admin@naver.com",
    password: "qwer1234!",
    avatarURL: "",
    admin: true,
    phone: "010-1234-1234",
    tel: "02-123-1234",
    birthDate: "1999.01.01",
    joinDate: "2024.12.01",
    startWorkTime: "09:00:00",
    finishWorkTime: "18:00:00",
    ogarnization: "디자인팀",
    duty: "BX 디자이너",
    level: "팀원",
  },
];

interface IWorkLog {
  date?: string;
  checkIn: string | null;
  checkOut: string | null;
  status: "정상" | "지각" | "결근" | "휴가" | "휴일";
  breakTime: string | null;
  workTime: string | null;
  overtime: string | null;
  nightTime: string | null;
}

export interface IEmpWorkTime {
  name: string;
  position?: string;
  department: string;
  workLog: IWorkLog[];
}

export const tempAllEmpsLog: IEmpWorkTime[] = [
  {
    name: "김성은",
    position: "프론트엔드 개발자",
    department: "개발팀",
    workLog: [
      {
        date: "2025-10-01",
        checkIn: null,
        checkOut: null,
        status: "결근",
        breakTime: "1시간",
        overtime: null,
        workTime: null,
        nightTime: null,
      },
    ],
  },
  {
    name: "이현정",
    position: "BX 디자이너",
    department: "디자인팀",
    workLog: [
      {
        date: "2025-10-02",
        checkIn: "10:02",
        checkOut: "09:02",
        status: "지각",
        breakTime: "1시간",
        overtime: null,
        workTime: "00시간 00분",
        nightTime: null,
      },
    ],
  },
  {
    name: "정우성",
    position: "인사 관리자",
    department: "경영팀",
    workLog: [
      {
        date: "2025-10-01",
        checkIn: null,
        checkOut: null,
        status: "휴가",
        breakTime: "1시간",
        overtime: null,
        workTime: null,
        nightTime: null,
      },
    ],
  },
  {
    name: "이정재",
    position: "인사 관리자",
    department: "경영팀",
    workLog: [
      {
        date: "2025-10-01",
        checkIn: null,
        checkOut: null,
        status: "휴가",
        breakTime: "1시간",
        overtime: null,
        workTime: null,
        nightTime: null,
      },
    ],
  },
  {
    name: "김지호",
    position: "BX 디자이너",
    department: "디자인팀",
    workLog: [
      {
        date: "2025-10-01",
        checkIn: "09:02",
        checkOut: "18:09",
        status: "정상",
        breakTime: "1시간",
        overtime: null,
        workTime: "09시간 00분",
        nightTime: null,
      },
    ],
  },
  {
    name: "이신우",
    position: "퍼포먼스 마케터",
    department: "마케팅팀",
    workLog: [
      {
        date: "2025-10-01",
        checkIn: "08:24",
        checkOut: "22:24",
        status: "정상",
        breakTime: "1시간",
        overtime: "3시간 24분",
        workTime: "12시간 24분",
        nightTime: "24분",
      },
    ],
  },
];

export const tempDepartmentList = ["전체", "경영팀", "디자인팀", "개발팀", "영업팀", "마케팅팀", "부서선택", "부서선택"];

export const tempEmpWorkLogs: IEmpWorkTime[] = [
  {
    name: "김성은",
    position: "프론트엔드 개발자",
    department: "개발팀",
    workLog: [
      {
        date: "2025-10-01",
        checkIn: "09:02",
        checkOut: "18:11",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 11분",
        nightTime: "00시간 00분",
        workTime: "08시간 09분",
      },
      {
        date: "2025-10-02",
        checkIn: "09:05",
        checkOut: "18:25",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 25분",
        nightTime: "00시간 00분",
        workTime: "08시간 20분",
      },
      {
        date: "2025-10-03",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-04",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-05",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-06",
        checkIn: "09:01",
        checkOut: "18:08",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 08분",
        nightTime: "00시간 00분",
        workTime: "08시간 07분",
      },
      {
        date: "2025-10-07",
        checkIn: "09:10",
        checkOut: "18:30",
        status: "지각",
        breakTime: "1시간",
        overtime: "00시간 30분",
        nightTime: "00시간 00분",
        workTime: "08시간 20분",
      },
      {
        date: "2025-10-08",
        checkIn: "08:59",
        checkOut: "18:02",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 02분",
        nightTime: "00시간 00분",
        workTime: "08시간 03분",
      },
      {
        date: "2025-10-09",
        checkIn: "09:03",
        checkOut: "18:12",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 12분",
        nightTime: "00시간 00분",
        workTime: "08시간 09분",
      },
      {
        date: "2025-10-10",
        checkIn: "09:00",
        checkOut: "18:43",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 43분",
        nightTime: "00시간 00분",
        workTime: "08시간 43분",
      },
      {
        date: "2025-10-11",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-12",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-13",
        checkIn: "09:04",
        checkOut: "18:14",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 14분",
        nightTime: "00시간 00분",
        workTime: "08시간 10분",
      },
      {
        date: "2025-10-14",
        checkIn: "09:09",
        checkOut: "18:00",
        status: "지각",
        breakTime: "1시간",
        overtime: "00시간 00분",
        nightTime: "00시간 00분",
        workTime: "07시간 51분",
      },
      {
        date: "2025-10-15",
        checkIn: "09:00",
        checkOut: "19:11",
        status: "정상",
        breakTime: "1시간",
        overtime: "01시간 11분",
        nightTime: "00시간 00분",
        workTime: "09시간 11분",
      },
      {
        date: "2025-10-16",
        checkIn: "09:02",
        checkOut: "18:17",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 17분",
        nightTime: "00시간 00분",
        workTime: "08시간 15분",
      },
      {
        date: "2025-10-17",
        checkIn: "09:06",
        checkOut: "18:23",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 23분",
        nightTime: "00시간 00분",
        workTime: "08시간 17분",
      },
      {
        date: "2025-10-18",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-19",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-20",
        checkIn: "09:00",
        checkOut: "18:10",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 10분",
        nightTime: "00시간 00분",
        workTime: "08시간 10분",
      },
      {
        date: "2025-10-21",
        checkIn: "09:03",
        checkOut: "18:33",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 33분",
        nightTime: "00시간 00분",
        workTime: "08시간 30분",
      },
      {
        date: "2025-10-22",
        checkIn: "08:57",
        checkOut: "18:18",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 18분",
        nightTime: "00시간 00분",
        workTime: "08시간 21분",
      },
      {
        date: "2025-10-23",
        checkIn: "09:08",
        checkOut: "18:19",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 19분",
        nightTime: "00시간 00분",
        workTime: "08시간 11분",
      },
      {
        date: "2025-10-24",
        checkIn: "09:11",
        checkOut: "18:05",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 05분",
        nightTime: "00시간 00분",
        workTime: "07시간 54분",
      },
      {
        date: "2025-10-25",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-26",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-27",
        checkIn: "09:00",
        checkOut: "18:30",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 30분",
        nightTime: "00시간 00분",
        workTime: "08시간 30분",
      },
      {
        date: "2025-10-28",
        checkIn: "09:03",
        checkOut: "18:11",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 11분",
        nightTime: "00시간 00분",
        workTime: "08시간 08분",
      },
      {
        date: "2025-10-29",
        checkIn: "09:02",
        checkOut: "18:40",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 40분",
        nightTime: "00시간 00분",
        workTime: "08시간 38분",
      },
      {
        date: "2025-10-30",
        checkIn: "09:06",
        checkOut: "18:05",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 05분",
        nightTime: "00시간 00분",
        workTime: "07시간 59분",
      },
      {
        date: "2025-10-31",
        checkIn: "09:00",
        checkOut: "18:00",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 00분",
        nightTime: "00시간 00분",
        workTime: "08시간 00분",
      },
    ],
  },
  {
    name: "이현정",
    position: "BX 디자이너",
    department: "디자인팀",
    workLog: [
      {
        date: "2025-10-01",
        checkIn: "09:05",
        checkOut: "18:10",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 10분",
        nightTime: "00시간 00분",
        workTime: "08시간 05분",
      },
      {
        date: "2025-10-02",
        checkIn: "09:20",
        checkOut: "18:45",
        status: "지각",
        breakTime: "1시간",
        overtime: "00시간 45분",
        nightTime: "00시간 00분",
        workTime: "08시간 25분",
      },
      {
        date: "2025-10-03",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-04",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-05",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-06",
        checkIn: "09:10",
        checkOut: "18:25",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 25분",
        nightTime: "00시간 00분",
        workTime: "08시간 15분",
      },
      {
        date: "2025-10-07",
        checkIn: "09:32",
        checkOut: "18:05",
        status: "지각",
        breakTime: "1시간",
        overtime: "00시간 05분",
        nightTime: "00시간 00분",
        workTime: "07시간 33분",
      },
      {
        date: "2025-10-08",
        checkIn: "08:57",
        checkOut: "18:20",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 20분",
        nightTime: "00시간 00분",
        workTime: "08시간 23분",
      },
      {
        date: "2025-10-09",
        checkIn: "09:02",
        checkOut: "18:09",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 09분",
        nightTime: "00시간 00분",
        workTime: "08시간 07분",
      },
      {
        date: "2025-10-10",
        checkIn: "09:00",
        checkOut: "18:40",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 40분",
        nightTime: "00시간 00분",
        workTime: "08시간 40분",
      },
      {
        date: "2025-10-11",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-12",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-13",
        checkIn: "09:09",
        checkOut: "18:12",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 12분",
        nightTime: "00시간 00분",
        workTime: "08시간 03분",
      },
      {
        date: "2025-10-14",
        checkIn: "09:22",
        checkOut: "18:03",
        status: "지각",
        breakTime: "1시간",
        overtime: "00시간 03분",
        nightTime: "00시간 00분",
        workTime: "07시간 41분",
      },
      {
        date: "2025-10-15",
        checkIn: "09:03",
        checkOut: "19:12",
        status: "정상",
        breakTime: "1시간",
        overtime: "01시간 12분",
        nightTime: "00시간 00분",
        workTime: "09시간 09분",
      },
      {
        date: "2025-10-16",
        checkIn: "09:10",
        checkOut: "18:18",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 18분",
        nightTime: "00시간 00분",
        workTime: "08시간 08분",
      },
      {
        date: "2025-10-17",
        checkIn: "09:04",
        checkOut: "18:05",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 05분",
        nightTime: "00시간 00분",
        workTime: "08시간 01분",
      },
      {
        date: "2025-10-18",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-19",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-20",
        checkIn: "09:00",
        checkOut: "18:14",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 14분",
        nightTime: "00시간 00분",
        workTime: "08시간 14분",
      },
      {
        date: "2025-10-21",
        checkIn: "09:08",
        checkOut: "18:31",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 31분",
        nightTime: "00시간 00분",
        workTime: "08시간 23분",
      },
      {
        date: "2025-10-22",
        checkIn: "08:59",
        checkOut: "18:20",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 20분",
        nightTime: "00시간 00분",
        workTime: "08시간 21분",
      },
      {
        date: "2025-10-23",
        checkIn: "09:06",
        checkOut: "18:19",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 19분",
        nightTime: "00시간 00분",
        workTime: "08시간 13분",
      },
      {
        date: "2025-10-24",
        checkIn: "09:10",
        checkOut: "18:11",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 11분",
        nightTime: "00시간 00분",
        workTime: "08시간 01분",
      },
      {
        date: "2025-10-25",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-26",
        checkIn: null,
        checkOut: null,
        status: "휴일",
        breakTime: null,
        overtime: null,
        nightTime: null,
        workTime: null,
      },
      {
        date: "2025-10-27",
        checkIn: "09:04",
        checkOut: "18:26",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 26분",
        nightTime: "00시간 00분",
        workTime: "08시간 22분",
      },
      {
        date: "2025-10-28",
        checkIn: "09:00",
        checkOut: "18:14",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 14분",
        nightTime: "00시간 00분",
        workTime: "08시간 14분",
      },
      {
        date: "2025-10-29",
        checkIn: "09:05",
        checkOut: "18:39",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 39분",
        nightTime: "00시간 00분",
        workTime: "08시간 34분",
      },
      {
        date: "2025-10-30",
        checkIn: "09:11",
        checkOut: "18:09",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 09분",
        nightTime: "00시간 00분",
        workTime: "07시간 58분",
      },
      {
        date: "2025-10-31",
        checkIn: "09:00",
        checkOut: "18:00",
        status: "정상",
        breakTime: "1시간",
        overtime: "00시간 00분",
        nightTime: "00시간 00분",
        workTime: "08시간 00분",
      },
    ],
  },
];
